### PR TITLE
Support packages, fix logpath extension when not using syslog, support tokumx instance name

### PR DESCRIPTION
**Pull request by esmet**
- Store logs in /var/log/XYZ/XYZ.log
- Look for the mongod binary in /usr/bin if installing from packages
- Support tokumx (http://github.com/Tokutek/mongo) as a supported mongo distrubtion, service name tokumx.

### CODE REVIEW

**Comment by motns** [comment]
Hiya! First of all, thanks for the pull request - it's very much appreciated!
There are a few points to resolve before we can get this merged in:

**1. Installing from package**
I'm more than happy to go down the road of supporting packages next to direct downloads, but perhaps it would be cleaner to be more explicit about the mode of installation. Right now, you rely on the value of `package_name` to determine what to do at run time. Instead, I think we should add a new attribute `default['mongodb']['install']['method'] = 'download'`, which people can change to `"package"` to trigger the alternative behaviour.
Then we can re-structure the current attributes to have `['mongodb']['install']['download']` and `['mongodb']['install']['package']` as the two namespaces, with their respective settings under each. Just feels much cleaner.

Also, you don't seem to be adding a new repository, only installing the package. I know 10Gen (or MongoDB Inc. to be precise) have their own Apt and Yum repositories that you need to add before installing from packages - does TokuMX have it's own repo?
Either way, this needs to be included (using the `apt_repository` provider) for this to work predictably.

**2. Support in LWRP**
I noticed that you added an override in the `hipsnip_mongodb_mongod` provider, which replaces the instance name passed in with `"tokumx"` if TokuMX is installed on the machine. This essentially breaks support for TokuMX users wanting to use the LWRP to create an instance with an alternative name, or create multiple instances on the same box - say for testing a replica set (would this be a problem with TokuMX?).
From what I can tell this is just a naming issue, so a possible workaround is to introduce a new attribute `['mongodb']['default_instance_name']` that's set to `"mongod"` by default, but can be overridden to be `"tokumx"` in the `mongod` recipe, based on the `['mongodb']['install']['package']['distro']` attribute (from above). The value of that attribute would then be used in the LWRP, when the user picks "default" as the instance name. Would that make sense?

**3. Attribute access**
Could you please use strings instead of symbols when accessing node attributes? Being inconsistent violates FoodCritic rule `FC019`, which is why the tests fail in Travis CI.

**4. Tests**
Right now even the basic tests (`rake cookbook:test`) fail, but if you fix the point above that should be sorted.
More importantly, we'll need to add new test suites in Test Kitchen (`rake cookbook:full_test`) to cover the new installation scenarios. To test installation from package, just adding a new variation of the `mongod-recipe` suite with installation from package is probably sufficient. I'd be tempted to add additional versions of the `mongod-recipe-auth`, `replicaset-lwrp` and `replicaset-lwrp-auth` suites as well to test the setup with TokuMX - my understanding is that it's a drop-in replacement, but it's worth making sure that we're not doing anything too hacky during the setup that might break.

Right now I'm in the process of doing some final testing on the auth support, both on MongoDB `2.4` and `2.6.0-rc1`, before cutting the `1.2.0` release for this cookbook. It would be great if we could include your additions in that release as well.
If you need help with getting the above points sorted, please let me know!

**Comment by esmet** [comment]
Sure, let's reorganize it a bit. I'm still getting a feel for How Things Work in chef anyway.

Support for LWRP using default instance name makes sense (that's probably what I wanted to do originally but didn't figure it out right).

**Comment by motns** [comment]
Hi @esmet 
Just wanted to check if you're still working on this, and if you needed any help with it. I would quite like to have the package install support (including TokuMX), so if you're no longer have time to work on this, I can take over and implement it on our end. Let me know!

**Comment by esmet** [comment]
Hey - sorry, I've been focusing attention on porting some other chef code to work with tokumx recently and lost sight of this pull request. I will hold off working on this for now while we at Tokutek figure out our packaging a little more (the repo isn't public yet, packages are still evolving, etc).

**Comment by motns** [comment]
No worries. Maybe then in the meantime I'll add support for installing from packages for the vanilla MongoDB distribution, and then we can tag on the TokuMX stuff later on when you're ready.
If that sounds alright with you then I'll close this pull request for now, and you can open a fresh one whenever you're ready.

**Comment by esmet** [comment]
Yup, that's the way to go.

**Pull request closed without merging**
